/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mma7;

import java.awt.Color;
import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ESCA
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    
    FeedForward vq=null;
    String path;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jButton4 = new javax.swing.JButton();
          jTextField1 = new javax.swing.JTextField();
          jButton1 = new javax.swing.JButton();
          jLabel1 = new javax.swing.JLabel();
          jButton2 = new javax.swing.JButton();
          jButton3 = new javax.swing.JButton();
          jLabel2 = new javax.swing.JLabel();

          jButton4.setText("jButton4");

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setBackground(new java.awt.Color(255, 153, 51));
          setSize(new java.awt.Dimension(200, 200));

          jTextField1.setBackground(new java.awt.Color(0, 0, 0));
          jTextField1.setForeground(new java.awt.Color(255, 255, 255));
          jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
          jTextField1.setBorder(new javax.swing.border.MatteBorder(null));
          jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
          jTextField1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField1ActionPerformed(evt);
               }
          });
          jTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
               public void propertyChange(java.beans.PropertyChangeEvent evt) {
                    jTextField1PropertyChange(evt);
               }
          });

          jButton1.setFont(new java.awt.Font("Palace Script MT", 1, 48)); // NOI18N
          jButton1.setText("Select File Here");
          jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });
          jButton1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
               public void propertyChange(java.beans.PropertyChangeEvent evt) {
                    jButton1PropertyChange(evt);
               }
          });

          jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 11)); // NOI18N
          jLabel1.setText("Number of levels :");

          jButton2.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
          jButton2.setText("Compress");
          jButton2.setEnabled(false);
          jButton2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
               }
          });

          jButton3.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
          jButton3.setText("Decompress");
          jButton3.setEnabled(false);
          jButton3.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
               }
          });

          jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\FFDPCM\\FFDPCM\\natural.jpg")); // NOI18N

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(110, 110, 110)
                              .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(60, 60, 60)
                              .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(150, 150, 150)
                              .addComponent(jLabel1)
                              .addGap(31, 31, 31)
                              .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(60, 60, 60)
                              .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(70, 392, Short.MAX_VALUE))
               .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(170, 170, 170)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(208, 208, 208)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(54, Short.MAX_VALUE))
               .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          vq.decompress();
          jButton3.setEnabled(false);
          JOptionPane.showMessageDialog(null, "Decompressed Successfully",
               "Done",
               JOptionPane.INFORMATION_MESSAGE);
          System.exit(0);
     }//GEN-LAST:event_jButton3ActionPerformed

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          if(jTextField1.getText().equals("") ){
               JOptionPane.showMessageDialog(null, "write number of levels");
          }else{
               int NOL=Integer.parseInt(jTextField1.getText());
               vq=new FeedForward();
               vq.compress(path, NOL);
               JOptionPane.showMessageDialog(null,
                    "Nice ^_^ ,compressed to ( \"C:\\Users\\hp\\Documents\\NetBeansProjects\\FFDPCM\\FFDPCM \" )",
                    "Done",
                    JOptionPane.INFORMATION_MESSAGE);
               jButton3.setEnabled(true);
               jButton1.setEnabled(false);
               jButton2.setEnabled(false);
          }
     }//GEN-LAST:event_jButton2ActionPerformed

     private void jButton1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButton1PropertyChange
          // TODO add your handling code here:
     }//GEN-LAST:event_jButton1PropertyChange

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          JFileChooser fc = new JFileChooser();
          FileNameExtensionFilter filter =new FileNameExtensionFilter("image files","jpg");
          fc.setCurrentDirectory(new File("C:\\Users\\hp\\Documents\\NetBeansProjects\\FFDPCM\\FFDPCM"));
          fc.addChoosableFileFilter((javax.swing.filechooser.FileFilter) filter);
          fc.setDialogTitle("Choose the file to compress :");
          if(fc.showOpenDialog(this)== JFileChooser.APPROVE_OPTION){
               path=fc.getSelectedFile().getAbsolutePath();
               jLabel1.setText("Now Go to Compress");
               jButton2.setEnabled(true);
          }else{
               JOptionPane.showMessageDialog(null,"Nothing Selected");
          }
     }//GEN-LAST:event_jButton1ActionPerformed

     private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_jTextField1ActionPerformed

     private void jTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField1PropertyChange
          // TODO add your handling code here:
          
     }//GEN-LAST:event_jTextField1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        }
        );
    }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JButton jButton3;
     private javax.swing.JButton jButton4;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JTextField jTextField1;
     // End of variables declaration//GEN-END:variables
}
